name: thrhaly
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: 
  rive:
  flutter_svg:
  flutter_screenutil:
  animate_do: ^3.0.2
  page_transition: ^2.0.9
  pin_code_fields: ^7.4.0
  flutter_launcher_icons: ^0.11.0
  fluttertoast: ^8.1.1
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  device_preview:
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.jpg"
flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/rive/
    - assets/svg/

  fonts:
      - family: GE SS
        fonts:
          - asset: assets/fonts/GE_SS/ARBFONTS-GESSTEXTULTRALIGHT-ULTRALIGHT.OTF
            weight: 200
          - asset: assets/fonts/GE_SS/GE_SS_TEXT_LIGHT.OTF
            weight: 300
          - asset: assets/fonts/GE_SS/GE_SS_TEXT_MEDIUM.OTF
            weight: 400
          - asset: assets/fonts/GE_SS/GE_SS_TEXT_MEDIUM.OTF
            weight: 500
          - asset: assets/fonts/GE_SS/ARBFONTS-GE-SS-TEXT-BOLD.OTF
            weight: 600     
          - asset: assets/fonts/GE_SS/ARBFONTS-GE-SS-TEXT-BOLD.OTF
            weight: 700    
          - asset: assets/fonts/GE_SS/GE SS Two Bold.otf
            weight: 800    
          - asset:  assets/fonts/GE_SS/GE SS Two Bold.otf
            weight: 900                       
